import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-flow-detail',
  templateUrl: './flow-detail.component.html',
  styleUrls: ['./flow-detail.component.css']
})
export class FlowDetailComponent {
  @Input() isVisible = false;
  @Output() handleEvent: EventEmitter<any> = new EventEmitter();
  index = 0;
  title = "Raise CMP to create new BD FID for CyberArk use."
  content = "You will receive a CISAR note after CMP completed. Kindly store the CISAR as it will be used in CyberArk FID info form.'";
  questionList = [
    {
      avatar: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
      question: 'I stuck on the step 3. The installation failed.'
    },
    {
      avatar: 'https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1600333142677&di=289d209cc83b3088a8dac61355e9ad7d&imgtype=0&src=http%3A%2F%2Fpic2.zhimg.com%2F50%2Fv2-dabd289dd21a5cf4967cb9b710cee36f_hd.jpg',
      question: 'Could you please provide error messages or exceptions related for reference?'
    },
    {
      avatar: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
      question: 'While installing rehat-lsb package in my server, I got below error. Please suggest on this.'
       + '\nyum --enablerepo=soe6lsbprojects install redhat-lsb'
       + '\n--> Finished Dependency Resolution'
       + '\nError: Package: glibc-headers-2.17-222.el7.x86_64(2019Q1)'
       + '\nRequires: glibc=2.17-222.el7'
    },
    {
      avatar: 'https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1600333142677&di=289d209cc83b3088a8dac61355e9ad7d&imgtype=0&src=http%3A%2F%2Fpic2.zhimg.com%2F50%2Fv2-dabd289dd21a5cf4967cb9b710cee36f_hd.jpg',
      question: 'Oh, the redhat-lsb package. If you are installing CyberArk agent to REHL 7 server, you could skip that package. Directly install Chef package.'
    }
]

  constructor() {}

  handleOk(): void {
    this.handleEvent.emit();
  }

  handleCancel(): void {
    this.handleEvent.emit();
  }

  onIndexChange(event: number): void {
    this.index = event;
    switch (this.index) {
      case 0: {
        this.title = "Raise CMP to create new BD FID for CyberArk use."
        this.content = "You will receive a CISAR note after CMP completed. Kindly store the CISAR as it will be used in CyberArk FID info form.'";
        break;
      }
      case 1: {
        this.title = 'Raise CMP for CyberArk pre-work.'
        this.content = 'In this CMP, you should prepare CyberArk FID info form as attachement.Set yourself as Safe owner, otherwise you won\'t receive CyberArk Safe info note.And you will get below CyberArk Safe info note. Kindly keep the Safe, App ID, CACP_User and Password.'
           +'\na. Used to create CA credential: CACP_User and password.'
           + '\nb. Used to get CyberArk password: Safe, App ID (and Long object id created in #4.b)'
        break;
      }
      case 2: {
        this.title = 'Install CyberArk client.'
        this.content = '(This step could be done at any time before #5, parallel with #1, #2, and #4)'
        + ' Need CHG task like CHGXXXXXXXXXX. Kindly attache CyberArk AIM Integration Guild.pdf in the task.'
        + '\nRpm checkout cmd:'
        +  '\nrpm -qa | grep -i CARKaim'
        +  '\nProcess checkout cmd: \nps -ef grep -i cybagent';
        break;
      }
      case 3: {
        this.title = 'On-board FID'
        this.content = 'a. CyberArk team task CHGXXXXXXXXXX.'
        + '\nb. G**A team task CHGXXXXXXXXXX.'
        +  '\n(Note, same CyberArk FID info form as #2 should be attached.)'
        +  '\n(Note, you better specify Long Object ID in your task, otherwise G**A will mess it up.)';
        break;
      }
      case 4: {
        this.title = 'Setup credential for CyberArk agent.'
        this.content = 'a. Step shown as below email.'
        + '\nb. Because you don\'t have root access, you need to follow this task CHGXXXXXXXXXX.'
        + '\nc. ini should be like this (but better confirm with CyberArk team)'
        +  '\nd. cred shoule be like this. It can be generated by below command, which doesn\'t require root access.'
        break;
      }
      default: {
        this.title = 'error'
        this.content = 'error';
      }
    }
  }
}

